//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a Chugin boilerplate, generated by chugerate!
//-----------------------------------------------------------------------------

// this should align with the correct versions of these ChucK files
#include "chuck_dl.h"
#include "chuck_def.h"
#include "Sigmund.h"

// general includes
#include <math.h>

// declaration of chugin constructor
CK_DLL_CTOR(sigmund_ctor);
// declaration of chugin desctructor
CK_DLL_DTOR(sigmund_dtor);

// example of getter/setter
//CK_DLL_MFUN(sigmund_setParam);
CK_DLL_MFUN(sigmund_getFreq);
CK_DLL_MFUN(sigmund_getPower);

// for Chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICK(sigmund_tick);

// this is a special offset reserved for Chugin internal data
t_CKINT sigmund_data_offset = 0;

extern "C"
{
  extern void mayer_fft(int n, t_sample *real, t_sample *imag);
  extern void mayer_realfft(int n, t_sample *real);
  void sigmund_getrawpeaks(int npts, t_float *insamps,
			   int npeak, t_peak *peakv, int *nfound, t_float *power, t_float srate, int loud,
			   t_float hifreq);
  void sigmund_getpitch(int npeak, t_peak *peakv, t_float *freqp,
			t_float npts, t_float srate, t_float nharmonics, t_float amppower, int loud);
  void notefinder_doit(t_notefinder *x, t_float freq, t_float power,
		       t_float *note, t_float vibrato, int stableperiod, t_float powerthresh,
		       t_float growththresh, int loud);
  void sigmund_peaktrack(int ninpeak, t_peak *inpeakv, 
			 int noutpeak, t_peak *outpeakv, int loud);
} 

// class definition for internal Chugin data
// (note: this isn't strictly necessary, but serves as example
// of one recommended approach)
class Sigmund
{
public:
  // constructor
  Sigmund( t_CKFLOAT fs)
  {
    npts = NPOINTS_DEF;
    param1 = 6;
    param2 = 0.5;
    param3 = 0;
    hop = HOP_DEF;
    mode = MODE_STREAM;
    npeak = NPEAK_DEF;
    vibrato = VIBRATO_DEF;
    stabletime = STABLETIME_DEF;
    growth = GROWTH_DEF;
    minpower = MINPOWER_DEF;
    maxfreq = 1000000;
    loud = 0;
    srate = fs;
    trackv = 0;
    ntrack = 0;
    donote = dotracks = 0;
    dopitch = 1;
    inbuf = (SAMPLE*)malloc(sizeof(SAMPLE)*npts);
    for (int i=0; i<npts; i++)
      inbuf[i] = 0;
    inbufIndex = 0;
    freq = 0;
	power = 0;
	note = 0;
  }
  
  ~Sigmund()
  {
    for (int i=0; i<npts; i++)
      inbuf[i] = 0;
    delete inbuf;
  }
    
  // for Chugins extending UGen
  SAMPLE tick ( SAMPLE in )
  {
    // default: this passes whatever input is patched into Chugin
    // fill sample buffer
    inbuf[inbufIndex++] = in;
    if (inbufIndex >= npts)
      {
	inbufIndex = 0;
	// THE MAGIC HAPPENS!!
	t_peak *peakv = (t_peak *)alloca(sizeof(t_peak) * npeak);
	int nfound, i, cnt;
	sigmund_getrawpeaks(npts, inbuf, npeak, peakv,
			    &nfound, &power, srate, loud, maxfreq);
	if (dopitch)
	  sigmund_getpitch(nfound, peakv, &freq, npts, srate, 
					   param1, param2, loud);
	if (donote)
	  notefinder_doit(&notefinder, freq, power, &note, vibrato, 
					  1 + stabletime * 0.001 * srate / (t_float)hop,
					  exp(LOG10*0.1*(minpower - 100)), growth, loud);
	if (dotracks)
	  sigmund_peaktrack(nfound, peakv, ntrack, trackv, loud);
      }
	return in;
  }
    
  // get parameter example
  float getFreq() { return freq; }

  // get parameter example
  float getPower() { return power; }
  
private:
  // instance data
  t_float srate;       // sample rate 
  int mode;         // MODE_STREAM, etc. 
  int npts;         // number of points in analysis window 
  int npeak;        // number of peaks to find 
  int loud;         // debug level 
  int infill;       // number of points filled 
  int countdown;    // countdown to start filling buffer 
  int hop;          // samples between analyses  
  t_float maxfreq;    // highest-frequency peak to report  
  t_float vibrato;    // vibrato depth in half tones  
  t_float stabletime; // period of stability needed for note  
  t_float growth;     // growth to set off a new note  
  t_float minpower;   // minimum power, in DB, for a note  
  t_float param1;     // three parameters for temporary use 
  t_float param2;
  t_float param3;
  t_notefinder notefinder;  // note parsing state 
  t_peak *trackv;           // peak tracking state 
  int ntrack;               // number of peaks tracked 
  unsigned int dopitch:1;   // which things to calculate 
  unsigned int donote:1;
  unsigned int dotracks:1;
  t_float freq, power, note;
  SAMPLE* inbuf;
  unsigned int inbufIndex;
};


// query function: chuck calls this when loading the Chugin
// NOTE: developer will need to modify this function to
// add additional functions to this Chugin
CK_DLL_QUERY( Sigmund )
{
  // hmm, don't change this...
  QUERY->setname(QUERY, "Sigmund");
  
  // begin the class definition
  // can change the second argument to extend a different ChucK class
  QUERY->begin_class(QUERY, "Sigmund", "UGen");
  
  // register the constructor (probably no need to change)
  QUERY->add_ctor(QUERY, sigmund_ctor);
  // register the destructor (probably no need to change)
  QUERY->add_dtor(QUERY, sigmund_dtor);
  
  // for UGen's only: add tick function
  QUERY->add_ugen_func(QUERY, sigmund_tick, NULL, 1, 1);
  
  // NOTE: if this is to be a UGen with more than 1 channel, 
  // e.g., a multichannel UGen -- will need to use add_ugen_funcf()
  // and declare a tickf function using CK_DLL_TICKF
  
  // example of adding setter method
  //QUERY->add_mfun(QUERY, sigmund_setFreq, "float", "param");
  // example of adding argument to the above method
  //QUERY->add_arg(QUERY, "float", "arg");
  
  // example of adding getter method
  QUERY->add_mfun(QUERY, sigmund_getFreq, "float", "freq");

  // example of adding getter method
  QUERY->add_mfun(QUERY, sigmund_getPower, "float", "power");
  
  // this reserves a variable in the ChucK internal class to store 
  // referene to the c++ class we defined above
  sigmund_data_offset = QUERY->add_mvar(QUERY, "int", "@s_data", false);
  
  // end the class definition
  // IMPORTANT: this MUST be called!
  QUERY->end_class(QUERY);
  
  // wasn't that a breeze?
  return TRUE;
}


// implementation for the constructor
CK_DLL_CTOR(sigmund_ctor)
{
  // get the offset where we'll store our internal c++ class pointer
  OBJ_MEMBER_INT(SELF, sigmund_data_offset) = 0;
  
  // instantiate our internal c++ class representation
  Sigmund * bcdata = new Sigmund(API->vm->get_srate());
  
  // store the pointer in the ChucK object member
  OBJ_MEMBER_INT(SELF, sigmund_data_offset) = (t_CKINT) bcdata;
}


// implementation for the destructor
CK_DLL_DTOR(sigmund_dtor)
{
  // get our c++ class pointer
  Sigmund * bcdata = (Sigmund *) OBJ_MEMBER_INT(SELF, sigmund_data_offset);
  // check it
  if( bcdata )
    {
      // clean up
      delete bcdata;
      OBJ_MEMBER_INT(SELF, sigmund_data_offset) = 0;
      bcdata = NULL;
    }
}


// implementation for tick function
CK_DLL_TICK(sigmund_tick)
{
  // get our c++ class pointer
  Sigmund * c = (Sigmund *) OBJ_MEMBER_INT(SELF, sigmund_data_offset);
  
  // invoke our tick function; store in the magical out variable
  if(c) *out = c->tick(in);
  
  // yes
  return TRUE;
}

/*
// example implementation for setter
CK_DLL_MFUN(sigmund_setParam)
{
  // get our c++ class pointer
  Sigmund * bcdata = (Sigmund *) OBJ_MEMBER_INT(SELF, sigmund_data_offset);
  // set the return value
  RETURN->v_float = bcdata->setParam(GET_NEXT_FLOAT(ARGS));
  }*/

// example implementation for getter
CK_DLL_MFUN(sigmund_getFreq)
{
  // get our c++ class pointer
  Sigmund * bcdata = (Sigmund *) OBJ_MEMBER_INT(SELF, sigmund_data_offset);
  // set the return value
  RETURN->v_float = bcdata->getFreq();
}

// example implementation for getter
CK_DLL_MFUN(sigmund_getPower)
{
  // get our c++ class pointer
  Sigmund * bcdata = (Sigmund *) OBJ_MEMBER_INT(SELF, sigmund_data_offset);
  // set the return value
  RETURN->v_float = bcdata->getPower();
}
