//-----------------------------------------------------------------------------
// Entaro ChucK Developer!
// This is a Chugin boilerplate, generated by chugerate!
//-----------------------------------------------------------------------------

// this should align with the correct versions of these ChucK files
#include "chuck_dl.h"
#include "chuck_def.h"
#include "ladspa.h"
#include "utils.h"

// general includes
#include <stdio.h>
#include <limits.h>
#include <dlfcn.h>

// declaration of chugin constructor
CK_DLL_CTOR(ladspa_ctor);
// declaration of chugin desctructor
CK_DLL_DTOR(ladspa_dtor);

// example of getter/setter
CK_DLL_MFUN(ladspa_setParam);
CK_DLL_MFUN(ladspa_getParam);

CK_DLL_MFUN(ladspa_printLabel);

// for Chugins extending UGen, this is mono synthesis function for 1 sample
CK_DLL_TICK(ladspa_tick);

extern void * loadLADSPAPluginLibrary(const char * pcPluginFilename);
extern void * dlopenLADSPA(const char * pcFilename, int iFlag);

// this is a special offset reserved for Chugin internal data
t_CKINT ladspa_data_offset = 0;


// class definition for internal Chugin data
// (note: this isn't strictly necessary, but serves as example
// of one recommended approach)
class Ladspa
{
public:
    // constructor
    Ladspa( t_CKFLOAT fs)
    {
        m_param = 0;
    }

    // for Chugins extending UGen
    SAMPLE tick( SAMPLE in )
    {
        // default: this passes whatever input is patched into Chugin
        return in;
    }

    // set parameter example
    float setParam( t_CKFLOAT p )
    {
        m_param = p;
        return p;
    }

  void printLabel ( Chuck_String * p)
  {
	const char * pcPluginFilename = p->str.c_str();
	printf("Received %s\n", pcPluginFilename);
	pvPluginHandle = dlopen(pcPluginFilename, RTLD_NOW);
	dlerror();
	//pvPluginHandle = loadLADSPAPluginLibrary(pcPluginFilename);
	//dlerror();
	pfDescriptorFunction = (LADSPA_Descriptor_Function)dlsym(pvPluginHandle, "ladspa_descriptor");
	if (!pfDescriptorFunction) {
	  const char * pcError = dlerror();
	  if (pcError) 
		printf("Unable to find ladspa_descriptor() function in plugin file "
			   "\"%s\": %s.\n"
			   "Are you sure this is a LADSPA plugin file?\n", 
			   pcPluginFilename,
			   pcError);
	  //return 1;
	}
  }

  // get parameter example
  float getParam() { return m_param; }
    
private:
  // instance data
  float m_param;
  LADSPA_Descriptor_Function pfDescriptorFunction;
  const LADSPA_Descriptor * psDescriptor;
  LADSPA_PortRangeHintDescriptor iHintDescriptor;
  LADSPA_Data fBound;
  LADSPA_Data fDefault;
  unsigned long lPluginIndex;
  unsigned long lPortIndex;
  unsigned long lSpaceIndex;
  unsigned long lSpacePadding1;
  unsigned long lSpacePadding2;
  unsigned long lLength;
  void * pvPluginHandle;
};


// query function: chuck calls this when loading the Chugin
// NOTE: developer will need to modify this function to
// add additional functions to this Chugin
CK_DLL_QUERY( Ladspa )
{
    // hmm, don't change this...
    QUERY->setname(QUERY, "Ladspa");
    
    // begin the class definition
    // can change the second argument to extend a different ChucK class
    QUERY->begin_class(QUERY, "Ladspa", "UGen");

    // register the constructor (probably no need to change)
    QUERY->add_ctor(QUERY, ladspa_ctor);
    // register the destructor (probably no need to change)
    QUERY->add_dtor(QUERY, ladspa_dtor);
    
    // for UGen's only: add tick function
    QUERY->add_ugen_func(QUERY, ladspa_tick, NULL, 1, 1);
    
    // NOTE: if this is to be a UGen with more than 1 channel, 
    // e.g., a multichannel UGen -- will need to use add_ugen_funcf()
    // and declare a tickf function using CK_DLL_TICKF

    // example of adding setter method
    QUERY->add_mfun(QUERY, ladspa_setParam, "float", "param");
    // example of adding argument to the above method
    QUERY->add_arg(QUERY, "float", "arg");

    // example of adding setter method
    QUERY->add_mfun(QUERY, ladspa_printLabel, "void", "load");
    // example of adding argument to the above method
    QUERY->add_arg(QUERY, "string", "filename");

    // example of adding getter method
    QUERY->add_mfun(QUERY, ladspa_getParam, "float", "param");
    
    // this reserves a variable in the ChucK internal class to store 
    // referene to the c++ class we defined above
    ladspa_data_offset = QUERY->add_mvar(QUERY, "int", "@l_data", false);

    // end the class definition
    // IMPORTANT: this MUST be called!
    QUERY->end_class(QUERY);

    // wasn't that a breeze?
    return TRUE;
}


// implementation for the constructor
CK_DLL_CTOR(ladspa_ctor)
{
    // get the offset where we'll store our internal c++ class pointer
    OBJ_MEMBER_INT(SELF, ladspa_data_offset) = 0;
    
    // instantiate our internal c++ class representation
    Ladspa * bcdata = new Ladspa(API->vm->get_srate());
    
    // store the pointer in the ChucK object member
    OBJ_MEMBER_INT(SELF, ladspa_data_offset) = (t_CKINT) bcdata;
}


// implementation for the destructor
CK_DLL_DTOR(ladspa_dtor)
{
    // get our c++ class pointer
    Ladspa * bcdata = (Ladspa *) OBJ_MEMBER_INT(SELF, ladspa_data_offset);
    // check it
    if( bcdata )
    {
        // clean up
        delete bcdata;
        OBJ_MEMBER_INT(SELF, ladspa_data_offset) = 0;
        bcdata = NULL;
    }
}


// implementation for tick function
CK_DLL_TICK(ladspa_tick)
{
    // get our c++ class pointer
    Ladspa * c = (Ladspa *) OBJ_MEMBER_INT(SELF, ladspa_data_offset);
 
    // invoke our tick function; store in the magical out variable
    if(c) *out = c->tick(in);

    // yes
    return TRUE;
}


// example implementation for setter
CK_DLL_MFUN(ladspa_setParam)
{
    // get our c++ class pointer
    Ladspa * bcdata = (Ladspa *) OBJ_MEMBER_INT(SELF, ladspa_data_offset);
    // set the return value
    RETURN->v_float = bcdata->setParam(GET_NEXT_FLOAT(ARGS));
}


// example implementation for getter
CK_DLL_MFUN(ladspa_getParam)
{
    // get our c++ class pointer
    Ladspa * bcdata = (Ladspa *) OBJ_MEMBER_INT(SELF, ladspa_data_offset);
    // set the return value
    RETURN->v_float = bcdata->getParam();
}

// example implementation for setter
CK_DLL_MFUN(ladspa_printLabel)
{
    // get our c++ class pointer
    Ladspa * bcdata = (Ladspa *) OBJ_MEMBER_INT(SELF, ladspa_data_offset);
    // set the return value
    bcdata->printLabel(GET_NEXT_STRING(ARGS));
}
